In [109]:
import sys
import os
sys.path.append(os.getcwd())  # adds the root folder automatically
print(os.getcwd())

import importlib
import Returns.Utils
importlib.reload(Returns.Utils)

from Returns.Utils import * 
print(dir())

import Returns.Utils
print(dir(Returns.Utils))

# if nothing is printed then there is a problem..

c:\Users\louis\OneDrive\Documents\Dauphine_2025_2026\S2\Python\LAVANDIER_LINON_JOLIBOIS
['EURO_PORTFOLIO', 'In', 'Out', 'Returns', 'START_DATE', 'US_PORTFOLIO', 'Utils', '_', '_100', '_102', '_103', '_48', '_50', '_52', '_54', '_58', '_60', '_63', '_66', '_70', '_72', '_78', '_82', '_84', '_94', '__', '___', '__builtin__', '__builtins__', '__doc__', '__loader__', '__name__', '__package__', '__spec__', '__vsc_ipynb_file__', '_dh', '_i', '_i1', '_i10', '_i100', '_i101', '_i102', '_i103', '_i104', '_i105', '_i106', '_i107', '_i108', '_i109', '_i11', '_i12', '_i13', '_i14', '_i15', '_i16', '_i17', '_i18', '_i19', '_i2', '_i20', '_i21', '_i22', '_i23', '_i24', '_i25', '_i26', '_i27', '_i28', '_i29', '_i3', '_i30', '_i31', '_i32', '_i33', '_i34', '_i35', '_i36', '_i37', '_i38', '_i39', '_i4', '_i40', '_i41', '_i42', '_i43', '_i44', '_i45', '_i46', '_i47', '_i48', '_i49', '_i5', '_i50', '_i51', '_i52', '_i53', '_i54', '_i55', '_i56', '_i57', '_i58', '_i59', '_i6', '_i60', '_i61', '_i62', '_i63', '_i64', '_i65', '_i66', '_i67', '_i68', '_i69', '_i7', '_i70', '_i71', '_i72', '_i73', '_i74', '_i75', '_i76', '_i77', '_i78', '_i79', '_i8', '_i80', '_i81', '_i82', '_i83', '_i84', '_i85', '_i86', '_i87', '_i88', '_i89', '_i9', '_i90', '_i91', '_i92', '_i93', '_i94', '_i95', '_i96', '_i97', '_i98', '_i99', '_ih', '_ii', '_iii', '_oh', 'builtins', 'check_stock_availability', 'compute_correlation', 'compute_log_returns', 'compute_means', 'compute_returns', 'compute_rolling_sharpe_ratio', 'compute_rolling_volatility', 'compute_sharpe_ratio', 'compute_value_at_risk', 'compute_volatility', 'datetime', 'debugpy', 'df', 'euro_portfolio_df', 'exit', 'fetch_data', 'file', 'get_ipython', 'historical_SP500', 'historical_STOXX50E', 'importlib', 'ipykernel', 'open', 'os', 'pd', 'plt', 'quit', 'return_summary_table', 'rolling_plot_graph', 'sns', 'stock', 'sys', 'test', 'us_portfolio_df', 'yf']
['EURO_PORTFOLIO', 'START_DATE', 'US_PORTFOLIO', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'check_stock_availability', 'compute_correlation', 'compute_log_returns', 'compute_means', 'compute_returns', 'compute_rolling_sharpe_ratio', 'compute_rolling_volatility', 'compute_sharpe_ratio', 'compute_value_at_risk', 'compute_volatility', 'datetime', 'fetch_data', 'os', 'pd', 'plt', 'return_summary_table', 'rolling_plot_graph', 'sns', 'sys', 'yf']

On choisit ici 5 actions européennes et 5 actions états-uniennes pour lesquelles on va extraire les prix de clôture sur la période [...] via l'API [...]

In [ ]:
# european stocks of our portfolio
euro_portfolio_df = fetch_data(EURO_PORTFOLIO, START_DATE)

# american stocks of our portfolio 
us_portfolio_df = fetch_data(US_PORTFOLIO, START_DATE)

historical_SP500 = fetch_data(["^GSPC"], START_DATE)
historical_STOXX50E= fetch_data(["^STOXX50E"], START_DATE)

[*********************100%***********************]  2 of 2 completed
[*********************100%***********************]  2 of 2 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Price            Close                   High                    Low  \
Ticker            AAPL       NFLX        AAPL       NFLX        AAPL
Date
2022-01-03  178.103668  59.737000  178.955006  60.999001  173.895967
2022-01-04  175.843216  59.115002  179.013683  60.041000  175.275662
2022-01-05  171.165833  56.751999  176.303156  59.284000  170.891843
2022-01-06  168.308472  55.328999  171.537649  56.335999  167.956198
2022-01-07  168.474854  54.105999  170.402574  55.342999  167.359321

Price                        Open                Volume
Ticker           NFLX        AAPL       NFLX       AAPL      NFLX
Date
2022-01-03  59.056000  174.013387  60.561001  104487900  30675000
2022-01-04  58.160000  178.710339  59.991001   99310400  43931000
2022-01-05  56.688000  175.755177  59.200001   94537600  41487000
2022-01-06  54.201000  168.993445  55.433998   96904000  57118000
2022-01-07  53.821999  169.179402  54.945999   86709100  33829000

In [115]:

euro_portfolio_df.head()

Price           Close                  High                   Low             \
Ticker         BNP.PA     DBK.DE     BNP.PA     DBK.DE     BNP.PA     DBK.DE
Date
2022-01-03  45.376587  10.173615  45.591607  10.200511  45.228297   9.879560
2022-01-04  46.896557  10.482017  47.259867  10.528635  45.710242  10.175410
2022-01-05  46.955872  10.623666  47.652828  10.718696  46.955872  10.401331
2022-01-06  47.593513  10.892618  47.697316  10.984063  46.562899  10.489188
2022-01-07  47.823364  11.086266  47.838191  11.190261  47.148647  10.871103

Price            Open              Volume
Ticker         BNP.PA     DBK.DE   BNP.PA      DBK.DE
Date
2022-01-03  45.309857   9.920799  2177649   8813113.0
2022-01-04  45.732484  10.196925  3614427  13350463.0
2022-01-05  47.089330  10.503533  3910434  10367648.0
2022-01-06  46.696360  10.532221  3645405  14599870.0
2022-01-07  47.452641  11.053991  3446590  13200588.0

In [116]:
us_portfolio_df.head()

Price            Close                   High                    Low  \
Ticker            AAPL       NFLX        AAPL       NFLX        AAPL
Date
2022-01-03  178.103668  59.737000  178.955006  60.999001  173.895967
2022-01-04  175.843216  59.115002  179.013683  60.041000  175.275662
2022-01-05  171.165833  56.751999  176.303156  59.284000  170.891843
2022-01-06  168.308472  55.328999  171.537649  56.335999  167.956198
2022-01-07  168.474854  54.105999  170.402574  55.342999  167.359321

Price                        Open                Volume
Ticker           NFLX        AAPL       NFLX       AAPL      NFLX
Date
2022-01-03  59.056000  174.013387  60.561001  104487900  30675000
2022-01-04  58.160000  178.710339  59.991001   99310400  43931000
2022-01-05  56.688000  175.755177  59.200001   94537600  41487000
2022-01-06  54.201000  168.993445  55.433998   96904000  57118000
2022-01-07  53.821999  169.179402  54.945999   86709100  33829000

In this part we will decide of a portefolio that maximises

On va désormais nettoyer les données avec compute_returns(), dans cette fonction on utilise : 
    - .fillna(method="ffill")   #permet de remplacer l
Now, we clean the data set to only keep the indexes, and Close for each stock.

We handle the missing values wiyh the function compute_returns(). We are using :
    - .fillna(method=interpolate) : through interpolation we are using interpolation to fill the voids due to week-ends and holidays. So we are smoothing the returns and avoiding big jumps in prices. But, it will probably cause a higher correlation beetween stocks, especially if they are from the same sector. A better approach would be to resample every stock but we won't do it here.

    -

Distribution Analysis

In [117]:
# histogram  simple returns

# histogram log-returns

Analysis ...